#!/usr/bin/env bash
# Per-file API diff for ODR-duplicate pairs between src/ and src_penta-core/.
# Emits a markdown report identifying which side has more public API surface
# and flagging pairs where the audit's "penta-core canonical" assumption is wrong.
#
# Usage:
#   scripts/audit/odr_pair_diff.sh > docs/CODEAUDIT_ODR_PAIR_DIFF_2026Q2.md
#
# See: docs/CODEAUDIT_CXX_DEEP_2026Q2_FOLLOWUP.md §1 (CRIT #1: ODR twins).

set -eu
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO"

PAIRS=(
    "harmony/ChordAnalyzer.cpp"
    "harmony/ChordAnalyzerSIMD.cpp"
    "harmony/HarmonyEngine.cpp"
    "harmony/ScaleDetector.cpp"
    "harmony/VoiceLeading.cpp"
    "osc/OSCClient.cpp"
    "osc/OSCHub.cpp"
    "osc/OSCMessage.cpp"
    "osc/OSCServer.cpp"
    "osc/RTMessageQueue.cpp"
    "groove/GrooveEngine.cpp"
    "groove/OnsetDetector.cpp"
    "groove/RhythmQuantizer.cpp"
    "groove/TempoEstimator.cpp"
)

# Extract method definitions: lines that look like a function definition with
# a Class::method( pattern, collapsed to just Class::method for diff purposes.
extract_api() {
    local file="$1"
    [ -f "$file" ] || { echo "(file missing)"; return; }
    # Match "Type Class::method(" and capture Class::method
    grep -hoE '[A-Za-z_][A-Za-z0-9_]*::[A-Za-z_~][A-Za-z0-9_]*\(' "$file" \
        | sed 's/($//' \
        | sort -u
}

# Is callsite from outside the pair-file referencing the src/ unique method?
# (Helps flag whether removing src/-only methods would break other code.)
find_callers() {
    local method="$1"; local pair="$2"
    grep -rln "\\b${method}\\b" src/ engine/ plugins/ bindings/ \
        --include='*.cpp' --include='*.h' --include='*.hpp' 2>/dev/null \
        | grep -vE "^(src|src_penta-core)/${pair}" \
        | head -3
}

cat <<'HEADER'
# ODR Pair Diff Report — harmony / osc / groove Consolidation

Generated by `scripts/audit/odr_pair_diff.sh`. Per-file comparison of the
14 duplicate .cpp files between `src/` and `src_penta-core/`. Both sides
compile into separate static libs and both link into `bindings/penta_core_native`,
creating a real ODR violation per `CODEAUDIT_CXX_DEEP_2026Q2_FOLLOWUP.md §1`.

The audit prescribed "src_penta-core/ canonical, delete src/ duplicates" —
but actual code shows some src/ files have **strictly more methods** than
their penta-core counterparts. Deleting those would break linkage (verified
experimentally on 2026-04-13: `penta::harmony::VoiceLeading::voiceProgression(vector<Chord>, ...)`
is called from `KellyCore/ChordGenerator.cpp` and only defined in `src/`).

**Per-pair recommended canonical side below.** `src/only` methods that have
external callers are flagged explicitly — those MUST be preserved.

---

HEADER

for rel in "${PAIRS[@]}"; do
    a="src/$rel"
    b="src_penta-core/$rel"
    a_methods=$(extract_api "$a")
    b_methods=$(extract_api "$b")
    a_count=$(echo "$a_methods" | grep -c . || true)
    b_count=$(echo "$b_methods" | grep -c . || true)

    only_a=$(comm -23 <(echo "$a_methods") <(echo "$b_methods"))
    only_b=$(comm -13 <(echo "$a_methods") <(echo "$b_methods"))
    both=$(comm -12 <(echo "$a_methods") <(echo "$b_methods"))
    only_a_count=$(echo "$only_a" | grep -c . || true)
    only_b_count=$(echo "$only_b" | grep -c . || true)
    both_count=$(echo "$both" | grep -c . || true)

    # Canonical heuristic:
    #  - Missing file → other side canonical
    #  - src/only has external callers → src/ canonical (preserves callers)
    #  - src_penta-core has more methods and src/only has no callers → penta canonical
    #  - Otherwise → manual
    canonical="MANUAL"
    note=""
    if [ ! -f "$a" ]; then
        canonical="src_penta-core/ (src/ missing)"
    elif [ ! -f "$b" ]; then
        canonical="src/ (src_penta-core/ missing)"
    else
        caller_hits=0
        if [ -n "$only_a" ]; then
            while IFS= read -r m; do
                [ -z "$m" ] && continue
                callers=$(find_callers "$m" "$rel")
                if [ -n "$callers" ]; then
                    caller_hits=$((caller_hits + 1))
                fi
            done <<< "$only_a"
        fi
        if [ "$caller_hits" -gt 0 ]; then
            canonical="**src/** (has $caller_hits method(s) called externally that src_penta-core/ lacks)"
        elif [ "$only_b_count" -gt "$only_a_count" ]; then
            canonical="src_penta-core/"
        elif [ "$only_a_count" -gt "$only_b_count" ]; then
            canonical="src/"
        else
            # API-equivalent — check byte equality
            if cmp -s "$a" "$b"; then
                canonical="**either (BYTE-IDENTICAL)** — auto-resolvable, pick either, delete other"
            else
                # Diverged impl. Compare line counts as a quality hint.
                a_lines=$(wc -l < "$a" | tr -d ' ')
                b_lines=$(wc -l < "$b" | tr -d ' ')
                # Most-recently-touched (excluding lockfile noise)
                a_mtime=$(stat -f '%m' "$a" 2>/dev/null || stat -c '%Y' "$a")
                b_mtime=$(stat -f '%m' "$b" 2>/dev/null || stat -c '%Y' "$b")
                if [ "$a_mtime" -gt "$b_mtime" ]; then
                    newer="src/ (mtime newer)"
                else
                    newer="src_penta-core/ (mtime newer)"
                fi
                canonical="**MANUAL REVIEW** — APIs match but bodies differ ($a_lines vs $b_lines lines; $newer)"
            fi
        fi
    fi

    echo "## $rel"
    echo ""
    echo "| side | methods | size |"
    echo "|------|---------|------|"
    a_size=$([ -f "$a" ] && wc -c < "$a" | tr -d ' ' || echo "0")
    b_size=$([ -f "$b" ] && wc -c < "$b" | tr -d ' ' || echo "0")
    echo "| \`src/\` | $a_count | $a_size B |"
    echo "| \`src_penta-core/\` | $b_count | $b_size B |"
    echo ""
    echo "**Recommended canonical**: $canonical"
    echo ""

    if [ -n "$only_a" ] && [ "$only_a_count" -gt 0 ]; then
        echo "### Only in \`src/$rel\` ($only_a_count)"
        echo ""
        while IFS= read -r m; do
            [ -z "$m" ] && continue
            callers=$(find_callers "$m" "$rel")
            if [ -n "$callers" ]; then
                echo "- \`$m\` — **called from**:"
                echo "$callers" | sed 's/^/    - /'
            else
                echo "- \`$m\` (no external callers)"
            fi
        done <<< "$only_a"
        echo ""
    fi

    if [ -n "$only_b" ] && [ "$only_b_count" -gt 0 ]; then
        echo "### Only in \`src_penta-core/$rel\` ($only_b_count)"
        echo ""
        while IFS= read -r m; do
            [ -z "$m" ] && continue
            echo "- \`$m\`"
        done <<< "$only_b"
        echo ""
    fi

    echo "### In both ($both_count)"
    echo ""
    if [ -n "$both" ] && [ "$both_count" -gt 0 ]; then
        echo "$both" | sed 's/^/- `/' | sed 's/$/`/'
    else
        echo "_(none)_"
    fi
    echo ""
    echo "---"
    echo ""
done

cat <<'FOOTER'
## Consolidation plan (derived)

After reviewing the above, for each pair the action is one of:

1. **src/ canonical** → add `list(FILTER KELLY_CORE_SOURCES EXCLUDE REGEX)`
   for the `src_penta-core/` counterpart in `src_penta-core/CMakeLists.txt`
   (or delete the penta file). Ensure `penta_core` target still compiles
   without it (check its own internal callers).

2. **src_penta-core/ canonical** → add `list(FILTER KELLY_CORE_SOURCES EXCLUDE
   REGEX)` for the `src/` counterpart in the root `CMakeLists.txt`, and add
   `penta_core` as a `PUBLIC` link dep of `KellyCore`.

3. **Manual merge** → port missing methods from the non-canonical side into
   the canonical, verify byte-exact behaviour of shared methods, then proceed
   as (1) or (2).

4. **API-equivalent** → pick the side with better implementation quality
   (per `SALVAGE_CATALOG_2026Q2.md`, src_penta-core/ has more recent commits
   but this is per-file verified, not a blanket rule).

No file deletions performed by this report. Human review required before
CMakeLists.txt edits.
FOOTER
