#pragma once

// JucePlugin_* constants are typically generated by JUCE's juce_add_plugin
// CMake function. These are fallback definitions in case they're not generated.
#ifndef JucePlugin_Name
#define JucePlugin_Name "Kelly Emotion Processor"
#endif
#ifndef JucePlugin_Manufacturer
#define JucePlugin_Manufacturer "Kelly"
#endif
#ifndef JucePlugin_Desc
#define JucePlugin_Desc "Emotion-driven MIDI generation plugin"
#endif
#ifndef JucePlugin_Version
#define JucePlugin_Version "0.1.0"
#endif
#ifndef JucePlugin_VersionCode
#define JucePlugin_VersionCode 0x000100
#endif
#ifndef JucePlugin_VersionString
#define JucePlugin_VersionString "0.1.0"
#endif
#ifndef JucePlugin_VST3Category
#define JucePlugin_VST3Category "Fx|Synth"
#endif
#ifndef JucePlugin_ManufacturerCode
#define JucePlugin_ManufacturerCode 'Klly'
#endif
#ifndef JucePlugin_PluginCode
#define JucePlugin_PluginCode 'Klp1'
#endif

#include "engine/IntentPipeline.h"
#include <juce_audio_processors/juce_audio_processors.h>
// Note: KellyBrain.h is included via MLBridge.h (below)
// We don't include it directly to avoid type conflicts between Types.h and
// KellyTypes.h KellyBrain.h includes KellyTypes.h, while IntentPipeline.h
// includes Types.h
#include "common/Types.h"
#include "daiw/dsp_graph.hpp"
#include "daiw/gpu_scheduler.hpp"
#include "daiw/shared_ipc.hpp"
#include "midi/MidiBuilder.h"
#include "midi/MidiGenerator.h"
#include "ml/InferenceThreadManager.h"
#include "ml/MLFeatureExtractor.h"
#include "ml/MultiModelProcessor.h"
#include "ml/PluginLatencyManager.h"
#include "penta/common/RTState.h"
#include "penta/ml/AudioEmotionRunner.h"
#include "plugin/MasterEQProcessor.h"
#include "plugin/PluginState.h"
// Forward declare KellyBrain and MLIntentPipeline to avoid type conflicts
// (KellyBrain.h includes KellyTypes.h, while PluginProcessor uses Types.h)
// Include these headers only in PluginProcessor.cpp where conversions are
// handled
namespace kelly {
class KellyBrain;
class MLIntentPipeline;
} // namespace kelly
using KellyBrain = kelly::KellyBrain;
using MLIntentPipeline = kelly::MLIntentPipeline;
#include "penta/diagnostics/BlockLatencyInstrument.h"
#include <array>
#include <atomic>
#include <memory>
#include <mutex> // std::mutex, std::once_flag
#include <optional>

namespace kelly {

class PluginProcessor : public juce::AudioProcessor,
                        public juce::AudioProcessorValueTreeState::Listener,
                        public juce::AsyncUpdater,
                        public juce::Timer {
public:
  PluginProcessor();
  ~PluginProcessor() override;

  void prepareToPlay(double sampleRate, int samplesPerBlock) override;
  void releaseResources() override;

  bool isBusesLayoutSupported(const BusesLayout &layouts) const override;

  // RT contract: this callback must be allocation-free, lock-free, and
  // syscall-free on the hot path. When LLVM 20+ Clang is available
  // (KMIDI_ENABLE_RTSAN=ON), this contract becomes machine-checkable by
  // adding [[clang::nonblocking]] here. Apple Clang currently rejects
  // the attribute on virtual declarations even when __has_cpp_attribute
  // reports support, so it is left out until the toolchain catches up.
  void processBlock(juce::AudioBuffer<float> &,
                    juce::MidiBuffer &) noexcept override;

  /** Store device workgroup for realtime workers (Apple Silicon low-latency).
   */
  void
  audioWorkgroupContextChanged(const juce::AudioWorkgroup &workgroup) override;

  juce::AudioProcessorEditor *createEditor() override;
  bool hasEditor() const override { return true; }

  const juce::String getName() const override { return JucePlugin_Name; }

  bool acceptsMidi() const override { return true; }
  bool producesMidi() const override { return true; }
  bool isMidiEffect() const override { return true; }
  double getTailLengthSeconds() const override { return 0.0; }

  int getNumPrograms() override { return 1; }
  int getCurrentProgram() override { return 0; }
  void setCurrentProgram(int) override {}
  const juce::String getProgramName(int) override { return {}; }
  void changeProgramName(int, const juce::String &) override {}

  void getStateInformation(juce::MemoryBlock &destData) override;
  void setStateInformation(const void *data, int sizeInBytes) override;

  // Parameter version (for JUCE ParameterID)
  static constexpr int PARAM_VERSION = 1;

  // Parameter IDs
  static constexpr const char *PARAM_VALENCE = "valence";
  static constexpr const char *PARAM_AROUSAL = "arousal";
  static constexpr const char *PARAM_INTENSITY = "intensity";
  static constexpr const char *PARAM_COMPLEXITY = "complexity";
  static constexpr const char *PARAM_HUMANIZE = "humanize";
  static constexpr const char *PARAM_FEEL = "feel";
  static constexpr const char *PARAM_DYNAMICS = "dynamics";
  static constexpr const char *PARAM_BARS = "bars";
  static constexpr const char *PARAM_BYPASS = "bypass";
  static constexpr const char *PARAM_TECHNIQUE = "technique";
  static constexpr const char *PARAM_SONG_SECTION = "song_section";
  static constexpr const char *PARAM_SONG_AMOUNT = "song_amount";
  static constexpr const char *PARAM_USE_HOST_TEMPO = "use_host_tempo";
  static constexpr const char *PARAM_ML_INFLUENCE = "ml_influence";

  // Master EQ Parameter IDs
  static constexpr const char *PARAM_EQ_BYPASS = "eq_bypass";
  static constexpr const char *PARAM_AI_EQ_ENABLED = "ai_eq_enabled";
  static constexpr const char *PARAM_AI_EQ_INTENSITY = "ai_eq_intensity";
  static constexpr const char *PARAM_AI_EQ_LOCK_USER_BANDS =
      "ai_eq_lock_user_bands";

  // Per-band EQ parameters (6 bands: 0=LowCut, 1=LowShelf, 2-4=Parametric,
  // 5=HighShelf/Cut)
  static constexpr const char *PARAM_EQ_BAND_0_FREQ = "eq_band_0_freq";
  static constexpr const char *PARAM_EQ_BAND_0_ENABLED = "eq_band_0_enabled";
  static constexpr const char *PARAM_EQ_BAND_1_FREQ = "eq_band_1_freq";
  static constexpr const char *PARAM_EQ_BAND_1_GAIN = "eq_band_1_gain";
  static constexpr const char *PARAM_EQ_BAND_1_Q = "eq_band_1_q";
  static constexpr const char *PARAM_EQ_BAND_1_ENABLED = "eq_band_1_enabled";
  static constexpr const char *PARAM_EQ_BAND_2_FREQ = "eq_band_2_freq";
  static constexpr const char *PARAM_EQ_BAND_2_GAIN = "eq_band_2_gain";
  static constexpr const char *PARAM_EQ_BAND_2_Q = "eq_band_2_q";
  static constexpr const char *PARAM_EQ_BAND_2_ENABLED = "eq_band_2_enabled";
  static constexpr const char *PARAM_EQ_BAND_3_FREQ = "eq_band_3_freq";
  static constexpr const char *PARAM_EQ_BAND_3_GAIN = "eq_band_3_gain";
  static constexpr const char *PARAM_EQ_BAND_3_Q = "eq_band_3_q";
  static constexpr const char *PARAM_EQ_BAND_3_ENABLED = "eq_band_3_enabled";
  static constexpr const char *PARAM_EQ_BAND_4_FREQ = "eq_band_4_freq";
  static constexpr const char *PARAM_EQ_BAND_4_GAIN = "eq_band_4_gain";
  static constexpr const char *PARAM_EQ_BAND_4_Q = "eq_band_4_q";
  static constexpr const char *PARAM_EQ_BAND_4_ENABLED = "eq_band_4_enabled";
  static constexpr const char *PARAM_EQ_BAND_5_FREQ = "eq_band_5_freq";
  static constexpr const char *PARAM_EQ_BAND_5_GAIN = "eq_band_5_gain";
  static constexpr const char *PARAM_EQ_BAND_5_Q = "eq_band_5_q";
  static constexpr const char *PARAM_EQ_BAND_5_ENABLED = "eq_band_5_enabled";

  // Access APVTS
  juce::AudioProcessorValueTreeState &getAPVTS() { return apvts_; }

  // Access plugin state manager
  PluginState &getPluginState() { return pluginState_; }
  const PluginState &getPluginState() const { return pluginState_; }

  // Access intent pipeline for UI
  // NOTE: Returns non-owning reference. The thesaurus is thread-safe, but
  // process()/processJourney() should only be called from UI thread. For audio
  // thread access, use try_lock pattern. IntentPipeline owns EmotionThesaurus,
  // which is passed as non-owning pointer to VADSystem/VADCalculator. Lifetime
  // is guaranteed: IntentPipeline outlives all components that reference
  // thesaurus.
  IntentPipeline &getIntentPipeline() { return intentPipeline_; }
  const IntentPipeline &getIntentPipeline() const { return intentPipeline_; }

  // Generate MIDI from current parameters
  void generateMidi();

  // Get generated MIDI for export/drag
  // NOTE: Lock-free. Returns a reference to the currently active buffer slot.
  // Safe to call from the message/UI thread — the RT thread only reads the same
  // slot, two concurrent readers are always safe. Do not hold this reference
  // across a generateMidi() call; take a copy if you need a stable snapshot.
  const GeneratedMidi &getGeneratedMidi() const {
    return midiBuffers_[activeMidiBuffer_.load(std::memory_order_acquire)];
  }

  // Check if new MIDI is ready
  bool hasPendingMidi() const { return hasPendingMidi_.load(); }
  void clearPendingMidi() { hasPendingMidi_.store(false); }

  // Check if generation is in progress
  bool isGenerating() const { return isGenerating_.load(); }

  // Check if parameters have changed (for UI to show regeneration needed
  // indicator)
  bool hasParametersChanged() const { return parametersChanged_.load(); }
  bool isHostPlaying() const { return isHostPlaying_.load(); }

  // Get last processed emotion from wound text (for UI feedback)
  // Returns the emotion that was detected/used in the last generation
  std::optional<EmotionNode> getLastProcessedEmotion() const;

  // Set wound description from UI
  void setWoundDescription(const juce::String &description);

  // ML Inference methods
  void enableMLInference(bool enable);
  bool isMLInferenceEnabled() const { return mlInferenceEnabled_.load(); }

  // Set custom inference function (for RTNeural or other ML backends)
  // Note: InferenceFunction type removed - using callback interface instead
  // void setInferenceFunction(InferenceThreadManager::InferenceFunction fn);

  // Multi-Model ML access
  Kelly::ML::MultiModelProcessor &getMultiModelProcessor() {
    return multiModelProcessor_;
  }
  const Kelly::ML::MultiModelProcessor &getMultiModelProcessor() const {
    return multiModelProcessor_;
  }

  // Enable/disable individual ML models
  void setModelEnabled(Kelly::ML::ModelType type, bool enabled);
  bool isModelEnabled(Kelly::ML::ModelType type) const;

  // Set selected emotion ID from wheel
  void setSelectedEmotionId(int emotionId);

  // Set music theory settings from UI
  // These settings can override emotion-derived parameters
  void setMusicTheorySettings(const juce::String &key, const juce::String &mode,
                              int tempoBpm);

  // Get current music theory settings
  struct MusicTheorySettings {
    juce::String key = "C";
    juce::String mode = "Ionian";
    int tempoBpm = 120;
  };
  MusicTheorySettings getMusicTheorySettings() const;
  float getHostTempoBpm() const { return hostTempoBpm_.load(); }

  //==============================================================================
  // Project Save/Load (Phase 0: v1.0 Critical Features)
  //==============================================================================

  /**
   * Save current project to file.
   * Saves complete project state including plugin parameters, generated MIDI,
   * vocal notes, lyrics, and emotion selections.
   *
   * @param file Target file to save to
   * @return true if successful
   */
  bool saveCurrentProject(const juce::File &file);

  /**
   * Load project from file.
   * Restores complete project state including plugin parameters, generated
   * MIDI, vocal notes, lyrics, and emotion selections.
   *
   * @param file Source file to load from
   * @return true if successful
   */
  bool loadProject(const juce::File &file);

  /**
   * Get last error message from project save/load operation.
   *
   * @return Error message string, empty if no error
   */
  juce::String getProjectError() const { return projectError_; }

  // KellyBrain API methods (optional high-level API)
  void enableKellyBrainAPI(bool enable);
  bool isKellyBrainAPIEnabled() const { return useKellyBrainAPI_.load(); }
  kelly::KellyBrain &getKellyBrain();
  const kelly::KellyBrain &getKellyBrain() const;

  // MLBridge methods (audio-driven generation)
  void enableMLBridge(bool enable);
  bool isMLBridgeEnabled() const { return useMLBridge_.load(); }
  kelly::MLIntentPipeline &getMLBridge();
  const kelly::MLIntentPipeline &getMLBridge() const;

  // Master EQ access
  MasterEQProcessor &getMasterEQProcessor() { return masterEQProcessor_; }
  const MasterEQProcessor &getMasterEQProcessor() const {
    return masterEQProcessor_;
  }

  // T6.7: Non-owning access to the emotion runner for UI-thread telemetry.
  // Returns nullptr if ML inference is not enabled / runner not initialized.
  penta::ml::AudioEmotionRunner *getEmotionRunner() noexcept {
    return emotionRunner_.get();
  }

  // AudioProcessorValueTreeState::Listener
  void parameterChanged(const juce::String &parameterID,
                        float newValue) override;

  // AsyncUpdater
  void handleAsyncUpdate() override;

  // Timer
  void timerCallback() override;

private:
  // ---- DSP graph node wrappers ------------------------------------------
  //
  // The audio pipeline (ML lookahead → master EQ) is encoded as a DAG:
  //   mlPipelineNode_ → eqPipelineNode_
  //
  // Both nodes share access to the outer PluginProcessor (via setOwner) and
  // a side-channel pointer to the current juce::AudioBuffer (via setBuffer,
  // called every block). The DSPGraph orchestrates evaluation order; the
  // nodes invoke private helpers that own the actual DSP logic.
  //
  // Port shape: each node declares 1 input and 1 output port so the graph
  // can connect them with a control edge. The per-port float buffers go
  // unused — real audio flows through the side-channel AudioBuffer.

  class MLPipelineNode : public daiw::rt::DSPNode {
  public:
    void setOwner(PluginProcessor *owner) noexcept { owner_ = owner; }
    void setBuffer(juce::AudioBuffer<float> *buf) noexcept { buffer_ = buf; }
    void prepare(double, std::size_t) override {}
    void process(const float *const *, float *const *,
                 std::size_t numSamples) noexcept override;
    std::size_t num_inputs() const override { return 1; }
    std::size_t num_outputs() const override { return 1; }

  private:
    PluginProcessor *owner_ = nullptr;
    juce::AudioBuffer<float> *buffer_ = nullptr;
  };

  class EQPipelineNode : public daiw::rt::DSPNode {
  public:
    void setOwner(PluginProcessor *owner) noexcept { owner_ = owner; }
    void setBuffer(juce::AudioBuffer<float> *buf) noexcept { buffer_ = buf; }
    void prepare(double, std::size_t) override {}
    void process(const float *const *, float *const *,
                 std::size_t numSamples) noexcept override;
    std::size_t num_inputs() const override { return 1; }
    std::size_t num_outputs() const override { return 1; }

  private:
    PluginProcessor *owner_ = nullptr;
    juce::AudioBuffer<float> *buffer_ = nullptr;
  };

  // RT-safe helpers executed by the graph nodes.
  void processMLChain_(juce::AudioBuffer<float> &buffer) noexcept;
  void processEQChain_(juce::AudioBuffer<float> &buffer) noexcept;

  //==============================================================================
  // Thread Safety Architecture
  //==============================================================================
  //
  // Audio Thread (processBlock):
  //   - MUST NEVER BLOCK — lock-free and allocation-free
  //   - No heap allocation (no vector grow, new, etc.); preallocate in
  //   prepareToPlay
  //   - Can read APVTS parameters atomically via getRawParameterValue()
  //   - Can read atomic flags (hasPendingMidi_, isGenerating_)
  //   - Reads midiBuffers_[activeMidiBuffer_.load(acquire)] — no lock ever
  //
  // Message/UI Thread:
  //   - Can block on locks (std::lock_guard)
  //   - Can call generateMidi(), setWoundDescription(), etc.
  //   - Can access IntentPipeline (which may do heavy processing)
  //
  // Parameter Automation:
  //   - APVTS parameters are thread-safe and lock-free
  //   - parameterChanged() is called from message thread
  //   - Audio thread reads via getRawParameterValue() (atomic)
  //
  //==============================================================================

  juce::AudioProcessorValueTreeState apvts_;
  PluginState pluginState_;

  IntentPipeline intentPipeline_; // Default pipeline (always available for
                                  // backward compatibility)
  MidiGenerator midiGenerator_;
  MidiBuilder midiBuilder_;

  // Optional high-level APIs (using pointers to avoid including headers with
  // conflicting types)
  std::unique_ptr<kelly::KellyBrain>
      kellyBrain_; // High-level API wrapper (optional)
  std::unique_ptr<kelly::MLIntentPipeline>
      mlBridge_; // ML-to-Intent bridge (optional)
  std::atomic<bool> useKellyBrainAPI_{
      false}; // Use KellyBrain instead of IntentPipeline
  std::atomic<bool> useMLBridge_{
      false}; // Use MLBridge for audio-driven generation

  // Lock-free double-buffer for MIDI data shared between the RT audio thread
  // (reader) and the message thread (writer).
  //
  // Protocol:
  //   Writer (non-RT): write to midiBuffers_[1 - activeMidiBuffer_.load()],
  //                    then activeMidiBuffer_.store(shadow, release).
  //   Reader (RT):     read from midiBuffers_[activeMidiBuffer_.load(acquire)].
  //
  // The RT thread never blocks, never allocates, and never touches the shadow
  // slot while the writer is updating it.
  std::array<GeneratedMidi, 2> midiBuffers_;
  std::atomic<int> activeMidiBuffer_{0};

  juce::MidiBuffer outputBuffer_;

  std::atomic<bool> hasPendingMidi_{false};
  std::atomic<bool> isGenerating_{false};

  // Parameter change tracking for manual regeneration
  // User requested manual regeneration only (no auto-regeneration during
  // playback)
  std::atomic<bool> parametersChanged_{false};

  // Real-time parameter regeneration support (kept for potential future use)
  std::atomic<bool> isHostPlaying_{false};
  std::atomic<bool> regenerationPending_{false};
  std::atomic<bool> autoRegenerateEnabled_{
      false}; // Disabled by default for manual regeneration
  static constexpr int DEBOUNCE_DELAY_MS = 200; // 200ms debounce delay

  // Protected by intentMutex_ - accessed from UI/message thread only
  // Read operations must hold lock, write operations already protected
  juce::String woundDescription_;
  std::optional<int> selectedEmotionId_;
  MusicTheorySettings musicTheorySettings_;
  std::optional<EmotionNode>
      lastProcessedEmotion_; // Last emotion processed from wound text

  mutable std::mutex
      intentMutex_; // Protects intentPipeline_, woundDescription_,
                    // selectedEmotionId_ Audio thread: use try_lock (never
                    // block) UI thread: use lock_guard (can block)

  double currentSampleRate_ = 44100.0;
  int currentBlockSize_ = 512;
  double playheadPosition_ = 0.0;
  double lastPpqPosition_ = 0.0; // Track last playhead position for scheduling

  // ML Inference components
  PluginLatencyManager latencyManager_;
  InferenceThreadManager inferenceManager_;
  MLFeatureExtractor featureExtractor_;
  Kelly::ML::MultiModelProcessor multiModelProcessor_;
  std::unique_ptr<Kelly::ML::AsyncMLPipeline> asyncMLPipeline_;
  std::atomic<bool> mlInferenceEnabled_{false};

  // Master EQ processor
  MasterEQProcessor masterEQProcessor_;

  /** Device audio workgroup (set by host). Use for realtime worker join on
   * macOS. */
  juce::AudioWorkgroup audioWorkgroup_;

#if JUCE_MAC
  /** Ensures QoS is promoted to USER_INTERACTIVE only once per audio thread
   * lifetime. */
  std::once_flag qosSetOnce_;
#endif

  /** Per-block latency instrument — captures P50/P90/P99 processing times. */
  penta::diagnostics::BlockLatencyInstrument latencyInstrument_;

  // Lookahead buffer for ML inference
  static constexpr int ML_LOOKAHEAD_MS = 20;
  juce::AudioBuffer<float> lookaheadBuffer_;
  int lookaheadWritePos_ = 0;
  int lookaheadReadPos_ = 0;
  int lookaheadSamples_ = 0;
  size_t lookaheadMask_ = 0; // T6.1: power-of-two mask for wrap-free modulo

  // T6.3: Cached APVTS parameter pointers — populated once in prepareToPlay,
  // read every processBlock with memory_order_relaxed (no lock needed).
  std::atomic<float> *paramMlInfluence_ = nullptr;
  std::atomic<float> *paramValence_ = nullptr;
  std::atomic<float> *paramArousal_ = nullptr;
  std::atomic<float> *paramEqBypass_ = nullptr;
  std::atomic<float> *paramBypass_ = nullptr;

  // Current emotion state from ML inference
  std::atomic<float> mlValence_{0.0f};
  std::atomic<float> mlArousal_{0.0f};
  int64_t sampleCounter_ = 0;

  // AudioEmotionRunner — RT-safe JEPA emotion inference
  std::unique_ptr<penta::ml::AudioEmotionRunner> emotionRunner_;
  penta::RTState emotionRTState_;
  std::vector<float> monoMixBuffer_; // Pre-allocated scratch for mono downmix

  std::atomic<float> hostTempoBpm_{120.0f};

  // Feature extraction and emotion application
  std::array<float, 128> extractFeatures(const juce::AudioBuffer<float> &buffer,
                                         int startPos) noexcept;
  void applyEmotionVector(const std::array<float, 64> &emotionVector) noexcept;

  // Project management
  juce::String projectError_; // Last error from save/load operations

  // ---- RT foundation primitives ----------------------------------------
  //
  // Wiring strategy:
  //   - ipcRegion_   : owned shared-memory region. Created in the ctor with
  //                    a PID-suffixed name; processBlock publishes the RT
  //                    state mirror once per block. Unlinked in the dtor.
  //                    External observers (Python brain, MCP daemon,
  //                    telemetry) can attach without touching the audio
  //                    path.
  //   - gpuScheduler_: CPU-fallback inference dispatcher. Replaces nothing
  //                    today; provides the API surface so a follow-up PR
  //                    can swap inferenceManager_ behind it.
  //   - dspGraph_    : ML→EQ chain encoded as a DAG with two nodes
  //                    (mlPipelineNode_ → eqPipelineNode_). The graph is
  //                    built in prepareToPlay and driven every block from
  //                    processBlock; the inline chain has been retired.
  std::unique_ptr<daiw::ipc::SharedRegion> ipcRegion_;
  std::string ipcRegionName_;
  daiw::rt::CpuGpuScheduler<> gpuScheduler_;
  std::unique_ptr<daiw::rt::DSPGraph<8, 16>> dspGraph_;
  MLPipelineNode mlPipelineNode_;
  EQPipelineNode eqPipelineNode_;
  daiw::rt::NodeId mlNodeId_ = daiw::rt::kInvalidNodeId;
  daiw::rt::NodeId eqNodeId_ = daiw::rt::kInvalidNodeId;

  static juce::AudioProcessorValueTreeState::ParameterLayout
  createParameterLayout();

  JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PluginProcessor)
};

} // namespace kelly
