/* Intent IR v1 - Rust FFI Bindings
 * Auto-generated by cbindgen. Do not edit manually.
 */


#ifndef INTENT_IR_FFI_H
#define INTENT_IR_FFI_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Warning: this file is auto-generated. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "IntentIR.h"

#define INTENT_IR_VERSION 1

typedef enum IntentSource {
  UiDirect = 0,
  UiEdit = 1,
  MlText = 2,
  MlAudio = 3,
  Preset = 4,
  Automation = 5,
} IntentSource;

typedef struct IntentFrame IntentFrame;

/**
 * Builder for IntentFrame with method chaining
 */
typedef struct IntentFrameBuilder IntentFrameBuilder;

/**
 * Opaque builder handle
 */
typedef struct IntentFrameBuilderHandle {
  struct IntentFrameBuilder *builder;
} IntentFrameBuilderHandle;

/**
 * Validate an IntentFrame
 * Returns 0 on success, error code on failure
 */
int validate_intent_frame_ffi(const struct IntentFrame *frame);

/**
 * Clamp all float values in an IntentFrame to valid ranges
 * Modifies frame in-place
 */
void clamp_intent_frame_ffi(struct IntentFrame *frame);

/**
 * Check if version is supported
 */
bool intent_frame_version_supported_ffi(uint16_t version);

/**
 * Create a new IntentFrameBuilder
 */
struct IntentFrameBuilderHandle *create_intent_frame_builder(void);

/**
 * Free an IntentFrameBuilder
 */
void IntentFrameBuilder_free(struct IntentFrameBuilderHandle *handle);

/**
 * Set emotion on builder
 */
void IntentFrameBuilder_set_emotion(struct IntentFrameBuilderHandle *handle,
                                    float valence,
                                    float arousal,
                                    float dominance,
                                    int16_t discrete_id,
                                    float intensity,
                                    float confidence);

/**
 * Set musical intent on builder
 */
void IntentFrameBuilder_set_musical_intent(struct IntentFrameBuilderHandle *handle,
                                           float tempo_bias,
                                           float rhythmic_density,
                                           float groove_strength,
                                           float harmonic_tension,
                                           float harmonic_motion,
                                           int8_t mode_preference,
                                           float melodic_activity,
                                           float contour_variance,
                                           float dynamic_range,
                                           float texture_density);

/**
 * Set time scope on builder
 */
void IntentFrameBuilder_set_time_scope(struct IntentFrameBuilderHandle *handle,
                                       int32_t start_bar,
                                       int32_t end_bar,
                                       float fade_in_beats,
                                       float fade_out_beats);

/**
 * Set constraints on builder
 */
void IntentFrameBuilder_set_constraints(struct IntentFrameBuilderHandle *handle,
                                        uint32_t allowed_engines_mask,
                                        uint32_t forbidden_engines_mask,
                                        float max_cpu_cost,
                                        float max_event_rate);

/**
 * Set provenance on builder
 */
void IntentFrameBuilder_set_provenance(struct IntentFrameBuilderHandle *handle,
                                       enum IntentSource source,
                                       float user_override_weight);

/**
 * Build the IntentFrame from builder
 * Returns 0 on success, error code on failure
 * On success, frame_out is populated
 * Note: Builder is consumed on call (success or failure)
 */
int IntentFrameBuilder_build(struct IntentFrameBuilderHandle *handle,
                             struct IntentFrame *frame_out);

#endif  /* INTENT_IR_FFI_H */
