/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */

export type EmotionTag = 'tension' | 'release' | 'warm' | 'cold' | 'bright' | 'dark' | 'drive' | 'float';

export interface EmotionState {
  /** Negative to positive [-1, 1] */
  valence?: number;
  /** Calm to excited [0, 1] */
  arousal?: number;
  /** Submissive to dominant [0, 1] */
  dominance?: number;
  /** Max 3 tags from controlled vocabulary */
  tags?: EmotionTag[];
  /** Inference quality gate [0, 1] */
  confidence?: number;
}
