/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */

export interface StructureSection {
  name: string;
  bars: number;
  repetitions?: number;
}

export interface TrackIntent {
  instrument: string;
  techniques?: string[];
}

export interface CompleteSongIntentRequest {
  core_desire: string;
  mood_primary: string;
  genre: string;
  tempo?: number;
  key_mode: string;
  structure: StructureSection[];
  instruments: TrackIntent[];
  allow_legacy_fallback?: boolean;
  groove_feel?: string;
  narrative_arc?: string;
  rule_to_break?: unknown;
  rule_justification?: unknown;
}
