/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */

import { EmotionState, EmotionTag } from "./EmotionState";

export type SectionRole = "intro" | "verse" | "chorus" | "bridge" | "outro" | "build" | "drop" | "";

export interface DSPTargets {
  filter_cutoff: number;
  filter_cutoff_confidence: number;
  reverb_send: number;
  reverb_send_confidence: number;
  drive: number;
  drive_confidence: number;
  /** True if DSP values are not yet valid */
  stale: boolean;
}

export interface IntentConstraints {
  allowed_engines_mask: number;
  forbidden_engines_mask: number;
  max_cpu_cost: number;
  max_event_rate: number;
}

export interface IntentMeta {
  /** Schema version */
  schema_version: number;
  /** Monotonic intent ID */
  intent_id: number;
  /** Session ID */
  session_id: number;
}

export interface IntentProvenance {
  source: number;
  user_override_weight: number;
}

export interface MusicHints {
  /** Key (e.g. 'C', 'F#') */
  key: string;
  /** Tempo BPM (0 = unspecified) */
  tempo_bpm: number;
  /** Chord bias */
  chord_bias: string;
  /** Section role */
  section_role: SectionRole;
}

export interface MusicalIntent {
  tempo_bias: number;
  rhythmic_density: number;
  groove_strength: number;
  harmonic_tension: number;
  harmonic_motion: number;
  mode_preference: number;
  melodic_activity: number;
  contour_variance: number;
  dynamic_range: number;
  texture_density: number;
}

export interface TimeScope {
  /** Start bar (-1 = immediate) */
  start_bar: number;
  /** End bar (-1 = open-ended) */
  end_bar: number;
  fade_in_beats: number;
  fade_out_beats: number;
}

export interface IntentFrame {
  meta: IntentMeta;
  /** Monotonic ms since session start */
  timestamp_ms: number;
  emotion: EmotionState;
  music: MusicalIntent;
  music_hints: MusicHints;
  dsp_targets: DSPTargets;
  time: TimeScope;
  constraints: IntentConstraints;
  provenance: IntentProvenance;
  /** Max ms for RT engine */
  latency_budget_ms: number;
}
