/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */

export interface StructureSection {
  name: string;
  bars: number;
  repetitions?: number;
}

export interface TrackIntent {
  instrument: string;
  techniques?: string[];
}

export interface CompleteSongIntentRequest {
  core_desire: string;
  mood_primary: string;
  genre: string;
  tempo?: number;
  key_mode: string;
  structure: StructureSection[];
  instruments: TrackIntent[];
  allow_legacy_fallback?: boolean;
  /** Rhythmic feel (e.g. Straight/Driving). */
  groove_feel?: string;
  /** Energetic trajectory (e.g. Climb-to-Climax). */
  narrative_arc?: string;
  /** Intentional theory violation for effect. */
  rule_to_break?: string | null;
  /** Narrative reason for the rule break. */
  rule_justification?: string | null;
}
