#!/bin/bash
# =============================================================================
# Interactive Environment Setup Wizard
# =============================================================================
# Guides users through setting up their development environment
# Creates .env.local with user-specific configuration
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_LOCAL="$PROJECT_ROOT/.env.local"

echo "=========================================="
echo "KmiDi Environment Setup Wizard"
echo "=========================================="
echo ""

# Check if .env.local already exists
if [ -f "$ENV_LOCAL" ]; then
    read -p ".env.local already exists. Overwrite? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Setup cancelled."
        exit 0
    fi
    echo ""
fi

# Start building .env.local
cat > "$ENV_LOCAL" << 'EOF'
# =============================================================================
# Local Environment Overrides
# =============================================================================
# This file is git-ignored and contains your personal configuration
# Generated by scripts/setup-env.sh
# =============================================================================

EOF

# API Keys Section
echo "=== API Keys ==="
echo "Enter your API keys (press Enter to skip):"
echo ""

read -p "OPENAI_API_KEY: " openai_key
if [ -n "$openai_key" ]; then
    echo "OPENAI_API_KEY=$openai_key" >> "$ENV_LOCAL"
fi

read -p "ANTHROPIC_API_KEY: " anthropic_key
if [ -n "$anthropic_key" ]; then
    echo "ANTHROPIC_API_KEY=$anthropic_key" >> "$ENV_LOCAL"
fi

read -p "GOOGLE_API_KEY: " google_key
if [ -n "$google_key" ]; then
    echo "GOOGLE_API_KEY=$google_key" >> "$ENV_LOCAL"
fi

read -p "XAI_API_KEY: " xai_key
if [ -n "$xai_key" ]; then
    echo "XAI_API_KEY=$xai_key" >> "$ENV_LOCAL"
fi

read -p "GITHUB_TOKEN: " github_token
if [ -n "$github_token" ]; then
    echo "GITHUB_TOKEN=$github_token" >> "$ENV_LOCAL"
fi

echo ""

# Paths Section
echo "=== Paths & Directories ==="
echo "Enter custom paths (press Enter to use defaults):"
echo ""

read -p "KELLY_MODELS_PATH [./models]: " models_path
if [ -n "$models_path" ]; then
    echo "KELLY_MODELS_PATH=$models_path" >> "$ENV_LOCAL"
fi

read -p "PYTHON_MODEL_PATH [./models]: " python_models_path
if [ -n "$python_models_path" ]; then
    echo "PYTHON_MODEL_PATH=$python_models_path" >> "$ENV_LOCAL"
fi

echo ""

# Service URLs Section
echo "=== Service URLs ==="
read -p "KMIDI_API_URL [http://127.0.0.1:8000]: " api_url
if [ -n "$api_url" ]; then
    echo "KMIDI_API_URL=$api_url" >> "$ENV_LOCAL"
fi

echo ""

# Logging Section
echo "=== Logging Configuration ==="
read -p "RUST_LOG level [info]: " rust_log
if [ -n "$rust_log" ]; then
    echo "RUST_LOG=$rust_log" >> "$ENV_LOCAL"
fi

echo ""
echo "=========================================="
echo "Setup complete! Configuration saved to .env.local"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review .env.local and adjust as needed"
echo "2. Run: source scripts/load-env.sh"
echo "3. Run: scripts/validate-env.sh"
echo ""
