#!/usr/bin/env python3
"""Sync canonical engine entities to shared JSON/TypeScript/Rust contracts."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from music_brain.engine_api.schema import CompleteSongIntentRequest
from music_brain.engine_api.schema import EmotionStateSchema
from music_brain.engine_api.schema import IntentFrameSchema

SCHEMA_DIR = ROOT / "shared_schemas"
SCHEMA_PATH = SCHEMA_DIR / "CompleteSongIntentRequest.json"
# Backward-compatible alias for older scripts/workflows (DEPRECATED: do not overwrite).
LEGACY_SCHEMA_PATH = SCHEMA_DIR / "CompleteSongIntent.json"
TS_OUT = ROOT / "src" / "types" / "Intent.ts"
# Rust codegen now targets the engine/intent_ir crate (src-tauri was removed).
RUST_OUT = ROOT / "engine" / "intent_ir" / "src" / "generated" / "intent.rs"

EMOTION_SCHEMA_PATH = SCHEMA_DIR / "emotion_schema.json"
EMOTION_TS_OUT = ROOT / "src" / "types" / "EmotionState.ts"
EMOTION_RUST_OUT = ROOT / "engine" / "intent_ir" / "src" / "generated" / "emotion.rs"

INTENT_FRAME_SCHEMA_PATH = SCHEMA_DIR / "intent_frame_schema.json"
INTENT_FRAME_TS_OUT = ROOT / "src" / "types" / "IntentFrame.ts"
INTENT_FRAME_RUST_OUT = ROOT / "engine" / "intent_ir" / "src" / "generated" / "intent_frame.rs"


def _unwrap_anyof_nullable(node: Dict[str, Any]) -> Dict[str, Any] | None:
    """If *node* is ``anyOf: [{type: T}, {type: null}]`` return the non-null branch."""
    any_of = node.get("anyOf")
    if not isinstance(any_of, list) or len(any_of) != 2:
        return None
    non_null = [b for b in any_of if b.get("type") != "null"]
    if len(non_null) == 1:
        return non_null[0]
    return None


def _model_schema() -> Dict[str, Any]:
    if hasattr(CompleteSongIntentRequest, "model_json_schema"):
        return CompleteSongIntentRequest.model_json_schema()  # pydantic v2
    return CompleteSongIntentRequest.schema()  # pydantic v1


def _resolve_ref(ref: str, schema: Dict[str, Any]) -> Dict[str, Any]:
    parts = ref.lstrip("#/").split("/")
    node: Dict[str, Any] = schema
    for part in parts:
        node = node[part]
    return node


def _json_to_ts(name: str, node: Dict[str, Any], schema: Dict[str, Any]) -> str:
    if "$ref" in node:
        ref_name = node["$ref"].split("/")[-1]
        return ref_name

    nullable_inner = _unwrap_anyof_nullable(node)
    if nullable_inner is not None:
        return f"{_json_to_ts(name, nullable_inner, schema)} | null"

    node_type = node.get("type")
    if "enum" in node:
        return " | ".join(f'"{value}"' for value in node["enum"])
    if node_type == "string":
        return "string"
    if node_type in ("integer", "number"):
        return "number"
    if node_type == "boolean":
        return "boolean"
    if node_type == "array":
        item_type = _json_to_ts(name, node.get("items", {}), schema)
        return f"{item_type}[]"
    if node_type == "object":
        props = node.get("properties", {})
        required = set(node.get("required", []))
        lines = ["{"]
        for key, value in props.items():
            optional = "" if key in required else "?"
            desc = value.get("description")
            if desc:
                lines.append(f"  /** {desc} */")
            lines.append(f"  {key}{optional}: {_json_to_ts(key, value, schema)};")
        lines.append("}")
        return "\n".join(lines)
    return "unknown"


def _json_to_rust_type(node: Dict[str, Any], required: bool = True) -> str:
    if "$ref" in node:
        base = node["$ref"].split("/")[-1]
        return base if required else f"Option<{base}>"

    nullable_inner = _unwrap_anyof_nullable(node)
    if nullable_inner is not None:
        return f"Option<{_json_to_rust_type(nullable_inner, required=True)}>"

    node_type = node.get("type")
    if node_type == "string":
        base = "String"
    elif node_type in ("integer", "number"):
        base = "i64" if node_type == "integer" else "f64"
    elif node_type == "boolean":
        base = "bool"
    elif node_type == "array":
        item = _json_to_rust_type(node.get("items", {}), required=True)
        base = f"Vec<{item}>"
    else:
        base = "serde_json::Value"
    return base if required else f"Option<{base}>"


def _render_typescript(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        "/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */",
        "",
    ]
    for name, node in defs.items():
        lines.append(f"export interface {name} {_json_to_ts(name, node, schema)}")
        lines.append("")
    root_ts = _json_to_ts("CompleteSongIntentRequest", schema, schema)
    lines.append(f"export interface CompleteSongIntentRequest {root_ts}")
    lines.append("")
    return "\n".join(lines)


def _render_rust(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        "// AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually.",
        "use serde::{Deserialize, Serialize};",
        "",
    ]
    for name, node in defs.items():
        required = set(node.get("required", []))
        lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
        lines.append(f"pub struct {name} {{")
        for key, value in node.get("properties", {}).items():
            is_required = key in required
            field_type = _json_to_rust_type(value, is_required)
            if not is_required:
                lines.append("    #[serde(default)]")
            lines.append(f"    pub {key}: {field_type},")
        lines.append("}")
        lines.append("")

    required_root = set(schema.get("required", []))
    lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    lines.append("pub struct CompleteSongIntentRequest {")
    for key, value in schema.get("properties", {}).items():
        is_required = key in required_root
        field_type = _json_to_rust_type(value, is_required)
        if not is_required:
            lines.append("    #[serde(default)]")
        lines.append(f"    pub {key}: {field_type},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _emotion_schema() -> dict:
    if hasattr(EmotionStateSchema, "model_json_schema"):
        return EmotionStateSchema.model_json_schema()
    return EmotionStateSchema.schema()


def _render_emotion_typescript(schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [
        "/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */",
        "",
    ]

    # Emit the tag enum from $defs
    defs = schema.get("$defs", schema.get("definitions", {}))
    for def_name, def_node in defs.items():
        if "enum" in def_node:
            lines.append(f"export type {def_name} = {' | '.join(repr(v) for v in def_node['enum'])};")
            lines.append("")

    lines.append("export interface EmotionState {")
    for key, value in props.items():
        optional = "" if key in required else "?"
        desc = value.get("description", "")
        if desc:
            lines.append(f"  /** {desc} */")
        if key == "tags":
            lines.append(f"  {key}{optional}: EmotionTag[];")
        elif value.get("type") == "number":
            lines.append(f"  {key}{optional}: number;")
        else:
            lines.append(f"  {key}{optional}: {_json_to_ts(key, value, schema)};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _rust_literal(value: Any, node: Dict[str, Any]) -> str:
    """Convert a Python default value to a Rust literal string."""
    node_type = node.get("type")
    if isinstance(value, bool):
        return "true" if value else "false"
    if node_type == "integer":
        return str(int(value))
    if node_type == "number":
        s = repr(float(value))
        # Ensure it has a decimal point for f64
        if "." not in s and "e" not in s and "E" not in s:
            s += ".0"
        return s
    if node_type == "string":
        return f'String::new()' if value == "" else f'"{value}".to_string()'
    # fallback
    return f"{value}"


def _type_zero(node: Dict[str, Any]) -> Any:
    """Return the zero/empty value for a JSON Schema type."""
    t = node.get("type")
    if t == "integer":
        return 0
    if t == "number":
        return 0.0
    if t == "boolean":
        return False
    if t == "string":
        return ""
    if t == "array":
        return []
    return 0


def _render_emotion_rust(schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [
        "// AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually.",
        "use serde::{Deserialize, Serialize};",
        "",
    ]

    # Emit tag enum
    defs = schema.get("$defs", schema.get("definitions", {}))
    for def_name, def_node in defs.items():
        if "enum" in def_node:
            lines.append("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
            lines.append(f"pub enum {def_name} {{")
            for val in def_node["enum"]:
                variant = val.capitalize()
                lines.append(f'    #[serde(rename = "{val}")]')
                lines.append(f"    {variant},")
            lines.append("}")
            lines.append("")

    lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    lines.append("#[serde(deny_unknown_fields)]")
    lines.append("pub struct EmotionState {")
    for key, value in props.items():
        if key == "tags":
            lines.append("    #[serde(default)]")
            lines.append("    pub tags: Vec<EmotionTag>,")
        else:
            # All numeric fields are f64 with serde(default), not Option<f64>.
            # Pydantic v2 omits `required` when all fields have defaults,
            # but these are always present in valid emotion payloads.
            field_type = _json_to_rust_type(value, required=True)
            lines.append("    #[serde(default)]")
            lines.append(f"    pub {key}: {field_type},")
    lines.append("}")
    lines.append("")

    # Emit manual impl Default with schema defaults
    lines.append("impl Default for EmotionState {")
    lines.append("    fn default() -> Self {")
    lines.append("        Self {")
    for key, value in props.items():
        if key == "tags":
            lines.append("            tags: Vec::new(),")
        else:
            default_val = value.get("default", 0.0)
            lines.append(f"            {key}: {_rust_literal(default_val, value)},")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Add validate() impl
    lines.append("impl EmotionState {")
    lines.append("    pub fn validate(&self) -> Result<(), String> {")
    lines.append("        if self.valence < -1.0 || self.valence > 1.0 {")
    lines.append('            return Err(format!("valence {} out of range [-1.0, 1.0]", self.valence));')
    lines.append("        }")
    lines.append("        if self.arousal < 0.0 || self.arousal > 1.0 {")
    lines.append('            return Err(format!("arousal {} out of range [0.0, 1.0]", self.arousal));')
    lines.append("        }")
    lines.append("        if self.dominance < 0.0 || self.dominance > 1.0 {")
    lines.append('            return Err(format!("dominance {} out of range [0.0, 1.0]", self.dominance));')
    lines.append("        }")
    lines.append("        if self.confidence < 0.0 || self.confidence > 1.0 {")
    lines.append('            return Err(format!("confidence {} out of range [0.0, 1.0]", self.confidence));')
    lines.append("        }")
    lines.append("        if self.tags.len() > 3 {")
    lines.append('            return Err(format!("tags count {} exceeds max 3", self.tags.len()));')
    lines.append("        }")
    lines.append("        // Check tag uniqueness")
    lines.append("        for i in 0..self.tags.len() {")
    lines.append("            for j in (i+1)..self.tags.len() {")
    lines.append("                if self.tags[i] == self.tags[j] {")
    lines.append('                    return Err("duplicate tags".to_string());')
    lines.append("                }")
    lines.append("            }")
    lines.append("        }")
    lines.append("        Ok(())")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _intent_frame_schema() -> dict:
    if hasattr(IntentFrameSchema, "model_json_schema"):
        return IntentFrameSchema.model_json_schema()
    return IntentFrameSchema.schema()


# Sub-structs from $defs that are already generated by the emotion codegen
_EMOTION_DEFS = {"EmotionStateSchema", "EmotionTag"}

# Mapping from JSON Schema $defs name to stripped output name
def _strip_schema_suffix(name: str) -> str:
    return name[:-len("Schema")] if name.endswith("Schema") else name


def _resolve_ref_name(ref: str) -> str:
    """Extract and strip the type name from a $ref string."""
    raw = ref.split("/")[-1]
    return _strip_schema_suffix(raw)


def _json_type_to_ts(node: Dict[str, Any], schema: Dict[str, Any]) -> str:
    """Convert a JSON Schema node to a TypeScript type string."""
    if "$ref" in node:
        ref_name = _resolve_ref_name(node["$ref"])
        # EmotionState and EmotionTag are imported, not redefined
        return ref_name.replace("EmotionState", "EmotionState")
    if "enum" in node:
        return " | ".join(f'"{v}"' for v in node["enum"])
    t = node.get("type")
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        return f"{_json_type_to_ts(node.get('items', {}), schema)}[]"
    return "unknown"


def _render_intent_frame_typescript(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        '/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */',
        '',
        'import { EmotionState, EmotionTag } from "./EmotionState";',
        '',
    ]

    # Emit SectionRole as a string union type
    if "SectionRole" in defs:
        sr = defs["SectionRole"]
        variants = " | ".join(f'"{v}"' for v in sr["enum"])
        lines.append(f"export type SectionRole = {variants};")
        lines.append("")

    # Emit interfaces for each sub-struct (skip emotion defs and SectionRole)
    for def_name, def_node in defs.items():
        if def_name in _EMOTION_DEFS or def_name == "SectionRole":
            continue
        iface_name = _strip_schema_suffix(def_name)
        props = def_node.get("properties", {})
        lines.append(f"export interface {iface_name} {{")
        for key, value in props.items():
            desc = value.get("description", "")
            if desc:
                lines.append(f"  /** {desc} */")
            ts_type = _json_type_to_ts(value, schema)
            lines.append(f"  {key}: {ts_type};")
        lines.append("}")
        lines.append("")

    # Emit root IntentFrame interface
    root_props = schema.get("properties", {})
    lines.append("export interface IntentFrame {")
    for key, value in root_props.items():
        desc = value.get("description", "")
        if desc:
            lines.append(f"  /** {desc} */")
        ts_type = _json_type_to_ts(value, schema)
        lines.append(f"  {key}: {ts_type};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _json_type_to_rust(node: Dict[str, Any]) -> str:
    """Convert a JSON Schema node to a Rust type string for IntentFrame codegen."""
    if "$ref" in node:
        return _resolve_ref_name(node["$ref"])
    t = node.get("type")
    if t == "string":
        return "String"
    if t == "number":
        return "f64"
    if t == "integer":
        return "i64"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"Vec<{_json_type_to_rust(node.get('items', {}))}>"
    return "serde_json::Value"


def _render_intent_frame_rust(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        "// AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually.",
        "use serde::{Deserialize, Serialize};",
        "use super::emotion::{EmotionState, EmotionTag};",
        "",
    ]

    # Emit SectionRole enum
    if "SectionRole" in defs:
        sr = defs["SectionRole"]
        lines.append("#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]")
        lines.append("pub enum SectionRole {")
        for val in sr["enum"]:
            if val == "":
                variant = "Unspecified"
                lines.append("    #[default]")
            else:
                variant = val.capitalize()
            lines.append(f'    #[serde(rename = "{val}")]')
            lines.append(f"    {variant},")
        lines.append("}")
        lines.append("")

    # Emit structs for each sub-struct (skip emotion defs and SectionRole)
    for def_name, def_node in defs.items():
        if def_name in _EMOTION_DEFS or def_name == "SectionRole":
            continue
        struct_name = _strip_schema_suffix(def_name)
        props = def_node.get("properties", {})
        # Check if any property has a non-zero default
        has_nonzero = any(
            p.get("default") not in (None, 0, 0.0, False, "")
            for p in props.values()
        )
        if has_nonzero:
            lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
        else:
            lines.append("#[derive(Debug, Clone, Default, Serialize, Deserialize)]")
        lines.append("#[serde(deny_unknown_fields)]")
        lines.append(f"pub struct {struct_name} {{")
        for key, value in props.items():
            field_type = _json_type_to_rust(value)
            lines.append("    #[serde(default)]")
            lines.append(f"    pub {key}: {field_type},")
        lines.append("}")
        lines.append("")

        # Emit manual impl Default if needed
        if has_nonzero:
            lines.append(f"impl Default for {struct_name} {{")
            lines.append("    fn default() -> Self {")
            lines.append("        Self {")
            for key, value in props.items():
                if "$ref" in value:
                    # Reference types use their own Default
                    ref_name = _resolve_ref_name(value["$ref"])
                    lines.append(f"            {key}: {ref_name}::default(),")
                else:
                    default_val = value.get("default", _type_zero(value))
                    lines.append(f"            {key}: {_rust_literal(default_val, value)},")
            lines.append("        }")
            lines.append("    }")
            lines.append("}")
            lines.append("")

    # Emit root IntentFrame struct
    root_props = schema.get("properties", {})
    has_nonzero_root = any(
        p.get("default") not in (None, 0, 0.0, False, "")
        for p in root_props.values()
        if "$ref" not in p
    )
    if has_nonzero_root:
        lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    else:
        lines.append("#[derive(Debug, Clone, Default, Serialize, Deserialize)]")
    lines.append("#[serde(deny_unknown_fields)]")
    lines.append("pub struct IntentFrame {")
    for key, value in root_props.items():
        field_type = _json_type_to_rust(value)
        lines.append("    #[serde(default)]")
        lines.append(f"    pub {key}: {field_type},")
    lines.append("}")
    lines.append("")

    # Emit manual impl Default for IntentFrame if needed
    if has_nonzero_root:
        lines.append("impl Default for IntentFrame {")
        lines.append("    fn default() -> Self {")
        lines.append("        Self {")
        for key, value in root_props.items():
            if "$ref" in value:
                ref_name = _resolve_ref_name(value["$ref"])
                lines.append(f"            {key}: {ref_name}::default(),")
            else:
                default_val = value.get("default", _type_zero(value))
                lines.append(f"            {key}: {_rust_literal(default_val, value)},")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Add validate() impl — check ALL [0,1] clamped fields
    # Collect clamped fields from MusicalIntent
    musical_intent_props = {}
    dsp_targets_props = {}
    for dn, dnode in defs.items():
        sn = _strip_schema_suffix(dn)
        if sn == "MusicalIntent":
            musical_intent_props = dnode.get("properties", {})
        elif sn == "DSPTargets":
            dsp_targets_props = dnode.get("properties", {})

    lines.append("impl IntentFrame {")
    lines.append("    pub fn validate(&self) -> Result<(), String> {")
    lines.append("        if self.meta.schema_version != 1 {")
    lines.append('            return Err(format!("unsupported schema_version {}", self.meta.schema_version));')
    lines.append("        }")
    lines.append("        if self.music.tempo_bias < -1.0 || self.music.tempo_bias > 1.0 {")
    lines.append('            return Err(format!("tempo_bias {} out of range [-1.0, 1.0]", self.music.tempo_bias));')
    lines.append("        }")

    # Validate all [0,1] clamped fields in MusicalIntent
    for field_name, field_node in musical_intent_props.items():
        if field_name == "tempo_bias":
            continue  # already handled above
        ft = field_node.get("type")
        mn = field_node.get("minimum")
        mx = field_node.get("maximum")
        if ft == "number" and mn == 0.0 and mx == 1.0:
            lines.append(f"        if self.music.{field_name} < 0.0 || self.music.{field_name} > 1.0 {{")
            lines.append(f'            return Err(format!("{field_name} {{}} out of range [0.0, 1.0]", self.music.{field_name}));')
            lines.append("        }")

    # Validate all [0,1] clamped fields in DSPTargets
    for field_name, field_node in dsp_targets_props.items():
        ft = field_node.get("type")
        mn = field_node.get("minimum")
        mx = field_node.get("maximum")
        if ft == "number" and mn == 0.0 and mx == 1.0:
            lines.append(f"        if self.dsp_targets.{field_name} < 0.0 || self.dsp_targets.{field_name} > 1.0 {{")
            lines.append(f'            return Err(format!("{field_name} {{}} out of range [0.0, 1.0]", self.dsp_targets.{field_name}));')
            lines.append("        }")

    lines.append("        if self.provenance.source < 0 || self.provenance.source > 5 {")
    lines.append('            return Err(format!("source {} out of range [0, 5]", self.provenance.source));')
    lines.append("        }")
    lines.append("        if self.time.end_bar != -1 && self.time.start_bar != -1 && self.time.end_bar <= self.time.start_bar {")
    lines.append('            return Err(format!("end_bar {} must be > start_bar {}", self.time.end_bar, self.time.start_bar));')
    lines.append("        }")
    lines.append("        Ok(())")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def sync_intent_frame() -> None:
    schema = _intent_frame_schema()
    schema_payload = json.dumps(schema, indent=2) + "\n"
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    INTENT_FRAME_SCHEMA_PATH.write_text(schema_payload, encoding="utf-8")
    INTENT_FRAME_TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    INTENT_FRAME_TS_OUT.write_text(
        _render_intent_frame_typescript(schema), encoding="utf-8"
    )
    if INTENT_FRAME_RUST_OUT.parent.exists():
        INTENT_FRAME_RUST_OUT.write_text(
            _render_intent_frame_rust(schema), encoding="utf-8"
        )
        # Ensure mod.rs includes intent_frame
        mod_rs = INTENT_FRAME_RUST_OUT.parent / "mod.rs"
        if mod_rs.exists():
            content = mod_rs.read_text(encoding="utf-8")
            if "pub mod intent_frame;" not in content:
                content = content.rstrip("\n") + "\npub mod intent_frame;\n"
                mod_rs.write_text(content, encoding="utf-8")
        else:
            mod_rs.write_text("pub mod intent_frame;\n", encoding="utf-8")
        print("IntentFrame Rust contract written to:", INTENT_FRAME_RUST_OUT)
    else:
        print("IntentFrame Rust output skipped (dir not found):", INTENT_FRAME_RUST_OUT.parent)

    print("IntentFrame schema exported to:", INTENT_FRAME_SCHEMA_PATH)
    print("IntentFrame TypeScript contract written to:", INTENT_FRAME_TS_OUT)


def sync_emotion() -> None:
    schema = _emotion_schema()
    schema_payload = json.dumps(schema, indent=2) + "\n"
    EMOTION_SCHEMA_PATH.write_text(schema_payload, encoding="utf-8")
    EMOTION_TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    EMOTION_TS_OUT.write_text(_render_emotion_typescript(schema), encoding="utf-8")
    if EMOTION_RUST_OUT.parent.exists():
        EMOTION_RUST_OUT.write_text(_render_emotion_rust(schema), encoding="utf-8")
        print("Emotion Rust contract written to:", EMOTION_RUST_OUT)
    else:
        print("Emotion Rust output skipped (dir not found):", EMOTION_RUST_OUT.parent)

    print("Emotion schema exported to:", EMOTION_SCHEMA_PATH)
    print("Emotion TypeScript contract written to:", EMOTION_TS_OUT)


def sync_boundaries() -> None:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)

    schema = _model_schema()
    schema_payload = json.dumps(schema, indent=2) + "\n"
    SCHEMA_PATH.write_text(schema_payload, encoding="utf-8")
    # DO NOT OVERWRITE LEGACY_SCHEMA_PATH - it is a distinct internal contract.
    TS_OUT.write_text(_render_typescript(schema), encoding="utf-8")
    if RUST_OUT.parent.exists():
        RUST_OUT.write_text(_render_rust(schema), encoding="utf-8")
        print("Rust contract written to:", RUST_OUT)
    else:
        print("Rust output skipped (target dir not found):", RUST_OUT.parent)

    print("Schema exported to:", SCHEMA_PATH)
    print("TypeScript contract written to:", TS_OUT)
    print("Contract sync complete.")
    print("Next steps for CI:")
    print("-> python scripts/sync_entities.py")
    print("-> verify generated artifacts are committed")


if __name__ == "__main__":
    sync_boundaries()
    sync_emotion()
    sync_intent_frame()
