#!/usr/bin/env python3
"""Sync canonical engine entities to shared JSON/TypeScript/Rust contracts."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from music_brain.engine_api.schema import CompleteSongIntentRequest
from music_brain.engine_api.schema import EmotionStateSchema

SCHEMA_DIR = ROOT / "shared_schemas"
SCHEMA_PATH = SCHEMA_DIR / "CompleteSongIntentRequest.json"
# Backward-compatible alias for older scripts/workflows (DEPRECATED: do not overwrite).
LEGACY_SCHEMA_PATH = SCHEMA_DIR / "CompleteSongIntent.json"
TS_OUT = ROOT / "src" / "types" / "Intent.ts"
RUST_OUT = ROOT / "src-tauri" / "src" / "generated" / "intent.rs"

EMOTION_SCHEMA_PATH = SCHEMA_DIR / "emotion_schema.json"
EMOTION_TS_OUT = ROOT / "src" / "types" / "EmotionState.ts"
EMOTION_RUST_OUT = ROOT / "src-tauri" / "src" / "generated" / "emotion.rs"


def _unwrap_anyof_nullable(node: Dict[str, Any]) -> Dict[str, Any] | None:
    """If *node* is ``anyOf: [{type: T}, {type: null}]`` return the non-null branch."""
    any_of = node.get("anyOf")
    if not isinstance(any_of, list) or len(any_of) != 2:
        return None
    non_null = [b for b in any_of if b.get("type") != "null"]
    if len(non_null) == 1:
        return non_null[0]
    return None


def _model_schema() -> Dict[str, Any]:
    if hasattr(CompleteSongIntentRequest, "model_json_schema"):
        return CompleteSongIntentRequest.model_json_schema()  # pydantic v2
    return CompleteSongIntentRequest.schema()  # pydantic v1


def _resolve_ref(ref: str, schema: Dict[str, Any]) -> Dict[str, Any]:
    parts = ref.lstrip("#/").split("/")
    node: Dict[str, Any] = schema
    for part in parts:
        node = node[part]
    return node


def _json_to_ts(name: str, node: Dict[str, Any], schema: Dict[str, Any]) -> str:
    if "$ref" in node:
        ref_name = node["$ref"].split("/")[-1]
        return ref_name

    nullable_inner = _unwrap_anyof_nullable(node)
    if nullable_inner is not None:
        return f"{_json_to_ts(name, nullable_inner, schema)} | null"

    node_type = node.get("type")
    if "enum" in node:
        return " | ".join(f'"{value}"' for value in node["enum"])
    if node_type == "string":
        return "string"
    if node_type in ("integer", "number"):
        return "number"
    if node_type == "boolean":
        return "boolean"
    if node_type == "array":
        item_type = _json_to_ts(name, node.get("items", {}), schema)
        return f"{item_type}[]"
    if node_type == "object":
        props = node.get("properties", {})
        required = set(node.get("required", []))
        lines = ["{"]
        for key, value in props.items():
            optional = "" if key in required else "?"
            desc = value.get("description")
            if desc:
                lines.append(f"  /** {desc} */")
            lines.append(f"  {key}{optional}: {_json_to_ts(key, value, schema)};")
        lines.append("}")
        return "\n".join(lines)
    return "unknown"


def _json_to_rust_type(node: Dict[str, Any], required: bool = True) -> str:
    if "$ref" in node:
        base = node["$ref"].split("/")[-1]
        return base if required else f"Option<{base}>"

    nullable_inner = _unwrap_anyof_nullable(node)
    if nullable_inner is not None:
        return f"Option<{_json_to_rust_type(nullable_inner, required=True)}>"

    node_type = node.get("type")
    if node_type == "string":
        base = "String"
    elif node_type in ("integer", "number"):
        base = "i64" if node_type == "integer" else "f64"
    elif node_type == "boolean":
        base = "bool"
    elif node_type == "array":
        item = _json_to_rust_type(node.get("items", {}), required=True)
        base = f"Vec<{item}>"
    else:
        base = "serde_json::Value"
    return base if required else f"Option<{base}>"


def _render_typescript(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        "/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */",
        "",
    ]
    for name, node in defs.items():
        lines.append(f"export interface {name} {_json_to_ts(name, node, schema)}")
        lines.append("")
    root_ts = _json_to_ts("CompleteSongIntentRequest", schema, schema)
    lines.append(f"export interface CompleteSongIntentRequest {root_ts}")
    lines.append("")
    return "\n".join(lines)


def _render_rust(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        "// AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually.",
        "use serde::{Deserialize, Serialize};",
        "",
    ]
    for name, node in defs.items():
        required = set(node.get("required", []))
        lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
        lines.append(f"pub struct {name} {{")
        for key, value in node.get("properties", {}).items():
            is_required = key in required
            field_type = _json_to_rust_type(value, is_required)
            if not is_required:
                lines.append("    #[serde(default)]")
            lines.append(f"    pub {key}: {field_type},")
        lines.append("}")
        lines.append("")

    required_root = set(schema.get("required", []))
    lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    lines.append("pub struct CompleteSongIntentRequest {")
    for key, value in schema.get("properties", {}).items():
        is_required = key in required_root
        field_type = _json_to_rust_type(value, is_required)
        if not is_required:
            lines.append("    #[serde(default)]")
        lines.append(f"    pub {key}: {field_type},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _emotion_schema() -> dict:
    if hasattr(EmotionStateSchema, "model_json_schema"):
        return EmotionStateSchema.model_json_schema()
    return EmotionStateSchema.schema()


def _render_emotion_typescript(schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [
        "/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */",
        "",
    ]

    # Emit the tag enum from $defs
    defs = schema.get("$defs", schema.get("definitions", {}))
    for def_name, def_node in defs.items():
        if "enum" in def_node:
            lines.append(f"export type {def_name} = {' | '.join(repr(v) for v in def_node['enum'])};")
            lines.append("")

    lines.append("export interface EmotionState {")
    for key, value in props.items():
        optional = "" if key in required else "?"
        desc = value.get("description", "")
        if desc:
            lines.append(f"  /** {desc} */")
        if key == "tags":
            lines.append(f"  {key}{optional}: EmotionTag[];")
        elif value.get("type") == "number":
            lines.append(f"  {key}{optional}: number;")
        else:
            lines.append(f"  {key}{optional}: {_json_to_ts(key, value, schema)};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _render_emotion_rust(schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [
        "// AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually.",
        "use serde::{Deserialize, Serialize};",
        "",
    ]

    # Emit tag enum
    defs = schema.get("$defs", schema.get("definitions", {}))
    for def_name, def_node in defs.items():
        if "enum" in def_node:
            lines.append("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
            lines.append(f"pub enum {def_name} {{")
            for val in def_node["enum"]:
                variant = val.capitalize()
                lines.append(f'    #[serde(rename = "{val}")]')
                lines.append(f"    {variant},")
            lines.append("}")
            lines.append("")

    lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    lines.append("#[serde(deny_unknown_fields)]")
    lines.append("pub struct EmotionState {")
    for key, value in props.items():
        if key == "tags":
            lines.append("    #[serde(default)]")
            lines.append("    pub tags: Vec<EmotionTag>,")
        else:
            # All numeric fields are f64 with serde(default), not Option<f64>.
            # Pydantic v2 omits `required` when all fields have defaults,
            # but these are always present in valid emotion payloads.
            field_type = _json_to_rust_type(value, required=True)
            lines.append("    #[serde(default)]")
            lines.append(f"    pub {key}: {field_type},")
    lines.append("}")
    lines.append("")

    # Add validate() impl
    lines.append("impl EmotionState {")
    lines.append("    pub fn validate(&self) -> Result<(), String> {")
    lines.append("        if self.valence < -1.0 || self.valence > 1.0 {")
    lines.append('            return Err(format!("valence {} out of range [-1.0, 1.0]", self.valence));')
    lines.append("        }")
    lines.append("        if self.arousal < 0.0 || self.arousal > 1.0 {")
    lines.append('            return Err(format!("arousal {} out of range [0.0, 1.0]", self.arousal));')
    lines.append("        }")
    lines.append("        if self.dominance < 0.0 || self.dominance > 1.0 {")
    lines.append('            return Err(format!("dominance {} out of range [0.0, 1.0]", self.dominance));')
    lines.append("        }")
    lines.append("        if self.confidence < 0.0 || self.confidence > 1.0 {")
    lines.append('            return Err(format!("confidence {} out of range [0.0, 1.0]", self.confidence));')
    lines.append("        }")
    lines.append("        if self.tags.len() > 3 {")
    lines.append('            return Err(format!("tags count {} exceeds max 3", self.tags.len()));')
    lines.append("        }")
    lines.append("        Ok(())")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def sync_emotion() -> None:
    schema = _emotion_schema()
    schema_payload = json.dumps(schema, indent=2) + "\n"
    EMOTION_SCHEMA_PATH.write_text(schema_payload, encoding="utf-8")
    EMOTION_TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    EMOTION_RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    EMOTION_TS_OUT.write_text(_render_emotion_typescript(schema), encoding="utf-8")
    EMOTION_RUST_OUT.write_text(_render_emotion_rust(schema), encoding="utf-8")

    print("Emotion schema exported to:", EMOTION_SCHEMA_PATH)
    print("Emotion TypeScript contract written to:", EMOTION_TS_OUT)
    print("Emotion Rust contract written to:", EMOTION_RUST_OUT)


def sync_boundaries() -> None:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)

    schema = _model_schema()
    schema_payload = json.dumps(schema, indent=2) + "\n"
    SCHEMA_PATH.write_text(schema_payload, encoding="utf-8")
    # DO NOT OVERWRITE LEGACY_SCHEMA_PATH - it is a distinct internal contract.
    TS_OUT.write_text(_render_typescript(schema), encoding="utf-8")
    RUST_OUT.write_text(_render_rust(schema), encoding="utf-8")

    print("Schema exported to:", SCHEMA_PATH)
    print("TypeScript contract written to:", TS_OUT)
    print("Rust contract written to:", RUST_OUT)
    print("Contract sync complete.")
    print("Next steps for CI:")
    print("-> python scripts/sync_entities.py")
    print("-> verify generated artifacts are committed")


if __name__ == "__main__":
    sync_boundaries()
    sync_emotion()
