#!/usr/bin/env python3
"""Sync canonical engine entities to shared JSON/TypeScript/Rust contracts."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from music_brain.engine_api.schema import CompleteSongIntentRequest

SCHEMA_DIR = ROOT / "shared_schemas"
SCHEMA_PATH = SCHEMA_DIR / "CompleteSongIntentRequest.json"
# Backward-compatible alias for older scripts/workflows.
LEGACY_SCHEMA_PATH = SCHEMA_DIR / "CompleteSongIntent.json"
TS_OUT = ROOT / "src" / "types" / "Intent.ts"
RUST_OUT = ROOT / "src-tauri" / "src" / "generated" / "intent.rs"


def _model_schema() -> Dict[str, Any]:
    if hasattr(CompleteSongIntentRequest, "model_json_schema"):
        return CompleteSongIntentRequest.model_json_schema()  # pydantic v2
    return CompleteSongIntentRequest.schema()  # pydantic v1


def _resolve_ref(ref: str, schema: Dict[str, Any]) -> Dict[str, Any]:
    parts = ref.lstrip("#/").split("/")
    node: Dict[str, Any] = schema
    for part in parts:
        node = node[part]
    return node


def _json_to_ts(name: str, node: Dict[str, Any], schema: Dict[str, Any]) -> str:
    if "$ref" in node:
        ref_name = node["$ref"].split("/")[-1]
        return ref_name

    node_type = node.get("type")
    if "enum" in node:
        return " | ".join(f'"{value}"' for value in node["enum"])
    if node_type == "string":
        return "string"
    if node_type in ("integer", "number"):
        return "number"
    if node_type == "boolean":
        return "boolean"
    if node_type == "array":
        item_type = _json_to_ts(name, node.get("items", {}), schema)
        return f"{item_type}[]"
    if node_type == "object":
        props = node.get("properties", {})
        required = set(node.get("required", []))
        lines = ["{"]
        for key, value in props.items():
            optional = "" if key in required else "?"
            lines.append(f"  {key}{optional}: {_json_to_ts(key, value, schema)};")
        lines.append("}")
        return "\n".join(lines)
    return "unknown"


def _json_to_rust_type(node: Dict[str, Any], required: bool = True) -> str:
    if "$ref" in node:
        base = node["$ref"].split("/")[-1]
        return base if required else f"Option<{base}>"

    node_type = node.get("type")
    if node_type == "string":
        base = "String"
    elif node_type in ("integer", "number"):
        base = "i64" if node_type == "integer" else "f64"
    elif node_type == "boolean":
        base = "bool"
    elif node_type == "array":
        item = _json_to_rust_type(node.get("items", {}), required=True)
        base = f"Vec<{item}>"
    else:
        base = "serde_json::Value"
    return base if required else f"Option<{base}>"


def _render_typescript(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        "/* AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually. */",
        "",
    ]
    for name, node in defs.items():
        lines.append(f"export interface {name} {_json_to_ts(name, node, schema)}")
        lines.append("")
    lines.append(
        f"export interface CompleteSongIntentRequest {_json_to_ts('CompleteSongIntentRequest', schema, schema)}"
    )
    lines.append("")
    return "\n".join(lines)


def _render_rust(schema: Dict[str, Any]) -> str:
    defs = schema.get("$defs") or schema.get("definitions", {})
    lines = [
        "// AUTO-GENERATED by scripts/sync_entities.py. Do not edit manually.",
        "use serde::{Deserialize, Serialize};",
        "",
    ]
    for name, node in defs.items():
        required = set(node.get("required", []))
        lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
        lines.append(f"pub struct {name} {{")
        for key, value in node.get("properties", {}).items():
            field_type = _json_to_rust_type(value, key in required)
            lines.append(f"    pub {key}: {field_type},")
        lines.append("}")
        lines.append("")

    required_root = set(schema.get("required", []))
    lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
    lines.append("pub struct CompleteSongIntentRequest {")
    for key, value in schema.get("properties", {}).items():
        field_type = _json_to_rust_type(value, key in required_root)
        lines.append(f"    pub {key}: {field_type},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def sync_boundaries() -> None:
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)

    schema = _model_schema()
    schema_payload = json.dumps(schema, indent=2) + "\n"
    SCHEMA_PATH.write_text(schema_payload, encoding="utf-8")
    # Legacy alias: same structure as CompleteSongIntentRequest, but with its own title
    # so tooling that reads the file by title sees the correct name.
    legacy_schema = dict(schema)
    legacy_schema["title"] = "CompleteSongIntent"
    legacy_schema_payload = json.dumps(legacy_schema, indent=2) + "\n"
    LEGACY_SCHEMA_PATH.write_text(legacy_schema_payload, encoding="utf-8")
    TS_OUT.write_text(_render_typescript(schema), encoding="utf-8")
    RUST_OUT.write_text(_render_rust(schema), encoding="utf-8")

    print("Schema exported to:", SCHEMA_PATH)
    print("Legacy schema alias updated:", LEGACY_SCHEMA_PATH)
    print("TypeScript contract written to:", TS_OUT)
    print("Rust contract written to:", RUST_OUT)
    print("Next steps for CI:")
    print("-> python scripts/sync_entities.py")
    print("-> verify generated artifacts are committed")


if __name__ == "__main__":
    sync_boundaries()

